### ISSUE TITLE
Events aren't sent to the browser when using compression

### ISSUE THREAD

**Issue by danieler1981** [toverux/expresse#2] opened 2017-09-26 12:29 UTC
I'm not able to receive events in the browser.

**SERVER**
`
res.sse.event("firstPaint", "10"); // 
`

**CLIENT**

               `var source = new EventSource('/api/v1/get_SEE/test');

                source.addEventListener('message', function(e) {
                    console.log("message"); //  never fired
                }, false);

                source.addEventListener('open', function(e) {
                    // this is fired correctly when the page is opened
                    console.log("connection opened");
                }, false);

                source.addEventListener('error', function(e) {
                    if (e.readyState == EventSource.CLOSED) {
                        // this is fired correctly in the case
                        console.log("connection closed");
                    }
                }, false);`

**Comment by toverux** [comment] 2017-09-26 12:45
Hi @danieler1981 

That's because you should be using `source.addEventListener('firstPaint', ...)` :)

Named SSE events are part of the spec and are used by EventSource. 

From the readme:

```typescript
//=> Data messages (no event name, but defaults to 'message' in the browser).
res.sse.data(event);
//=> Named event + data (data is mandatory)
res.sse.event('someEvent', event);
//=> Comment, not interpreted by EventSource on the browser - useful for debugging/self-documenting purposes.
res.sse.comment('debug: someModule emitted someEvent!');
```

(I agree that I should add client-side examples)

So either replace `message` with `firstPaint`, or use `res.sse.data` server-side.
If you want to keep `message` client-side, use you own event structure:

```typescript
res.sse.data({ myType: 'firstPaint', myData: '10' });
```

**Comment by danieler1981** [comment] 2017-09-26 12:50
I was not reporting that part of the code, but I'm using it of course and do not work.

**Comment by toverux** [comment] 2017-09-26 12:56
Okay... that was not obvious indeed :)
Especially since you're showing an example with `addEventListener('message', ...)` and the comment `// never fired`. This is expected. Are you sure that the event names match?

If yes, can you please tell me what's your browser (with version), the polyfill you are using (if any), etc?

**Comment by danieler1981** [comment] 2017-09-26 13:13
Routing
`        this.server.get("/api/v1/getResult_SEE/:taskID", sse(), getWebSiteResult_SEE(this));
`

Routing function
```
    export function getWebSiteResult_SEE (_self: WebSiteManager_Front): any {

    return async function (req: Request, res: ISseResponse) {
        const taskID: string = req.params.taskID;
        console.log("getWebSiteResult_SEE_v2", "taskID="+taskID); **// it work**
        
        setInterval(function () {
            res.sse.event("firstPaint", "10");
            res.sse.data({ myType: 'firstPaint', myData: '10' });
            console.log("data.v7"); **// to check if is fired, and it is**
        }, 1000);
    }
}
```

CLIENT
```
var source = new EventSource('/api/v1/getWebSiteResult_SEE/daniele');

                source.addEventListener('firstPaint', function(e) {
                    console.log("firstPaint");
                }, false);

                source.addEventListener('message', function(e) {
                    console.log("message");
                }, false);

                source.addEventListener('open', function(e) {
                    // Connection was opened.
                    console.log("connection opened");
                }, false);

                source.addEventListener('error', function(e) {
                    if (e.readyState == EventSource.CLOSED) {
                        // Connection was closed.
                        console.log("connection closed");
                    }
                }, false); 
```

**Comment by danieler1981** [comment] 2017-09-26 13:15
Chrome 62 
OSX

**Comment by danieler1981** [comment] 2017-09-26 13:42
checked with Charles, no event is sent back to the browser. So i think there are some issue to write the data in the "response" not in the client.

**Comment by danieler1981** [comment] 2017-09-26 13:46
are you sure you are flush()ing your data?

**Comment by toverux** [comment] 2017-09-26 13:48
Thanks - that's strange. I'll look into that asap, hope I can reproduce.

In the meantime... maybe you check if the problem comes from some company proxy, antivirus, etc? Some are a bit outdated and don't permit non-classic HTTP responses. Or maybe some other software in the stack buffers the response, which should not happen with SSE.
I'd also be interested in what the Network debugging tool of Chrome says about the state of the request.

**Comment by toverux** [comment] 2017-09-26 13:50
Also, if you are using a gzip middleware, disable it on SSE endpoints. They won't work together.

**Comment by danieler1981** [comment] 2017-09-26 13:50
i'm not using any firewall or proxy, because other SSE demo is working fine.
Just forced a flush() event, and now it work.

Can you check "sse_middleware.js" a bit?

```
            event(event, data, id) {
                var a = res.write(fmt.message(event, data, id, serializer));
                res.flush();
            },

```

**Comment by toverux** [comment] 2017-09-26 13:55
Do you use https://expressjs.com/en/resources/middleware/compression.html ?
`res.flush()` is not a core Express method (res.write always writes to the socket direclty without buffering... except if another middleware hijacks it).

**Comment by danieler1981** [comment] 2017-09-26 13:58
of course i use Compression

**Comment by danieler1981** [comment] 2017-09-26 14:05
i will prevent Compression to work in SSE scenario. Maybe the library should also take care of it.

**Comment by toverux** [comment] 2017-09-26 14:09
Okay, that's why.
I can't just add `res.flush()` then.

I can still check if res.flush exists and if yes, call it. But that's not very deterministic, nothing guarantees that it's the compression middleware.

Instead, you should call `res.flush()` yourself just after `res.sse.*()` calls. Or disable compression on SSE endpoints, but that means you can't enable it once for the whole app.

I'm not sure it is the library's responsibility to handle that (compression + side effects of other middlewares...), but I'll think about it (maybe a new option).

That's cool we've catched that issue anyway!

**Comment by danieler1981** [comment] 2017-09-26 14:10
Compression has a filter function; just used it and it work.

**Comment by toverux** [comment] 2017-09-26 14:11
Oh, cool. Could you provide a snippet for this? I'll add that to the readme.

**Comment by danieler1981** [comment] 2017-09-26 14:21
```
app.use(compression({level: 7, filter: function (req, res) {                
                if(req.originalUrl.indexOf("getWebSiteResult_SSE")==-1) {
                    const isCompressible = compressible(res.getHeader('Content-Type'));
                    return isCompressible; // enable Compression depeneding on the content-type
                } else {
                    return false; // disable compression since you are approaching an SSE library
                }
            }}));
```

**Comment by toverux** [comment] 2017-09-26 14:23
Excellent. I'll update the readme and close the issue then. Thanks for your help @danieler1981.

**Comment by toverux** [comment] 2017-09-26 16:16
Readme updated.

**Closed as completed by toverux** 2017-09-26 16:16 UTC

**Comment by bchoii** [comment] 2020-11-21 18:25
To anyone reading this, there is another bypass. Instead of filtering the compression middleware, you can add header

'Cache-Control': 'no-transform'

for the same effect.

**Comment by toverux** [comment] 2020-11-21 22:41
Hi @bchoii, thanks for the feedback.

In the meantime the `flushAfterWrite` option was implemented to support the compression middleware. https://github.com/toverux/expresse#using-compression

Have you tried it?
